name: Cargo Publish
on:
  push:
    tags:
      - rust-*
  workflow_dispatch: null
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./icns-rs
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Publish
        run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_TOKEN }}